import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import useTranslation from '../../locales'
import Breadcrumb from '../../components/Breadcrumb'

const Home: NextPage = () => {
  const t = useTranslation()
  return (
    <>
      <Head>
        <title>a26.dev | {t('common:home')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon.ico" />
      </Head>

      <Navbar />

      <Breadcrumb />

      <section className="section">
        <div className="container">
          <div className="columns is-8 is-variable">
            <div className="column is-7-tablet">
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut
                facere ab qui aspernatur. Cumque placeat architecto officia
                impedit voluptatum. Odit doloremque voluptatibus possimus ullam
                reprehenderit dolore facere, quasi nulla quia!
              </p>
            </div>
            <div className="column  is-5-tablet">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, ex.
              Quo error modi in cum excepturi consectetur rem? Molestiae quis
              error est? Recusandae nam id deserunt suscipit, labore quis
              expedita?
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  )
}

export default Home
