import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const Home: NextPage = () => {
  const [isBurgerActive, setIsBurgerActive] = useState(false)

  return (
    <div>
      <Head>
        <title>a26.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon.ico" />
      </Head>

      <Navbar />

      <div className="section pt-4 pb-0">
        <nav className="breadcrumb has-arrow-separator">
          <ul className="container">
            <li>
              <a className="has-text-grey">Home</a>
            </li>
            <li className="is-active">
              <a>About</a>
            </li>
          </ul>
        </nav>
      </div>

      <section className="section">
        <div className="container">
          <div className="columns is-vcentered">
            <div className="column is-3 has-text-right">
              <h1 className="is-size-1 title">a26.dev</h1>
              <h2 className="is-size-2 subtitle">Free tools for ever</h2>
              <p>We develop digital tools to help with daily tasks</p>
            </div>
            <div className="column is-5">
              <Image
                src="/assets/undraw_home_screen_re_640d.svg"
                width={600}
                height={600}
              />
            </div>
            <div className="column is-4">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea,
              placeat eius iste commodi maxime veritatis tempore, ducimus
              accusamus ipsam, quaerat natus numquam nobis rem nisi nostrum
              provident quae reprehenderit quis?
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}

export default Home
