import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import useTranslation from '../locales'

const Home: NextPage = () => {
  const t = useTranslation()

  return (
    <>
      <Head>
        <title>
          {t('common:site-domain')} | {t('common:home')}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon.ico" />
      </Head>

      <Navbar />

      <section className="section">
        <div className="container">
          <div className="columns is-vcentered is-multiline">
            <div className="column is-6-tablet is-3-desktop has-text-right-desktop">
              <h1 className="is-size-1 title">{t('common:site-domain')}</h1>
              <h2 className="is-size-2 subtitle">{t('home:slogan')}</h2>
              <p>{t('home:subtitle')}</p>
            </div>
            <div className="column is-6-tablet is-5-desktop has-text-centered">
              <Image
                src="/assets/undraw_home_screen_re_640d.svg"
                alt={t('home:img-alt')}
                width={466}
                height={466}
              />
            </div>
            <div className="column is-12-tablet is-4-desktop">
              <div className="columns is-multiline">
                <div className="column is-6-tablet is-12-desktop">
                  <div className="is-size-4 mb-4">{t('home:cta-title')}</div>
                  <p>
                    {t('home:cta-description')}{' '}
                    <span className="has-text-weight-semibold">
                      {t('common:app-domain')}
                    </span>
                  </p>
                </div>
                <div className="column is-6-tablet is-12-desktop">
                  <a
                    href={`https://${t('common:app-domain')}`}
                    className="button is-primary is-fullwidth is-size-3 has-text-weight-semibold"
                  >
                    {t('home:cta-button')}
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  )
}

export default Home
