import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import useTranslation from '../locales'

const Home: NextPage = () => {
  const t = useTranslation()
  return (
    <>
      <Head>
        <title>
          {t('common:site-domain')} | {t('common:home')}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon.ico" />
      </Head>

      <Navbar />

      <section className="section">
        <div className="container">
          <div className="columns is-vcentered is-multiline">
            <div className="column is-6-tablet is-3-desktop has-text-right-desktop">
              <h1 className="is-size-1 title">{t('common:site-domain')}</h1>
              <h2 className="is-size-2 subtitle">{t('home:subtitls')}</h2>
              <p>We develop digital tools to help with daily tasks</p>
            </div>
            <div className="column is-6-tablet is-5-desktop has-text-centered">
              <Image
                src="/assets/undraw_home_screen_re_640d.svg"
                alt="An ilustration of a person holding apps"
                width={466}
                height={466}
              />
            </div>
            <div className="column is-12-tablet is-4-desktop">
              <div className="columns is-multiline">
                <div className="column is-6-tablet is-12-desktop">
                  <div className="is-size-4 mb-4">Check out the app list</div>
                  <p>
                    For easy and customizable access all the apps are available
                    at <span className="has-text-weight-semibold">a26.app</span>
                  </p>
                </div>
                <div className="column is-6-tablet is-12-desktop">
                  <a className="button is-primary is-fullwidth is-size-3 has-text-weight-semibold">
                    Go to a26.app
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  )
}

export default Home
